[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true


[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
[[language]]
name = "scss"
formatter = { command = 'prettier', args = ["--parser", "scss"] }
[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true


[[language]]
name = "gdscript"
formatter = { command = "gdformat", args = ["-"] }
auto-format = true


[[language]]
name = "typst"
formatter = { command = "typstfmt", args = ["--output", "-"] }
auto-format = true
